// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zacanxuybdaejwjagwwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphY2FueHV5YmRhZWp3amFnd3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NTE5MTUsImV4cCI6MjA1MzAyNzkxNX0.3rZv4PT2729aiiiPB8hqKZjyQfEavEviDTVB1ZKa7Sw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);